In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('HeartDisease.csv')
df.head(10)

age  gender  chest_pain  rest_bps  cholestrol  fasting_blood_sugar  \
0   63       1           3       145         233                    1   
1   37       1           2       130         250                    0   
2   41       0           1       130         204                    0   
3   56       1           1       120         236                    0   
4   57       0           0       120         354                    0   
5   57       1           0       140         192                    0   
6   56       0           1       140         294                    0   
7   44       1           1       120         263                    0   
8   52       1           2       172         199                    1   
9   57       1           2       150         168                    0   

   rest_ecg  thalach  exer_angina  old_peak  slope  ca  thalassemia  target  
0         0      150            0       2.3      0   0            1       1  
1         1      187            0       3.5      0   0            2       1  
2         0      172            0       1.4      2   0            2       1  
3         1      178            0       0.8      2   0            2       1  
4         1      163            1       0.6      2   0            2       1  
5         1      148            0       0.4      1   0            1       1  
6         0      153            0       1.3      1   0            2       1  
7         1      173            0       0.0      2   0            3       1  
8         1      162            0       0.5      2   0            3       1  
9         1      174            0       1.6      2   0            2       1

In [12]:
df.isnull().sum()

age           0
gender        0
rest_bps      0
cholestrol    0
target        0
dtype: int64

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   age                  303 non-null    int64  
 1   gender               303 non-null    int64  
 2   chest_pain           303 non-null    int64  
 3   rest_bps             303 non-null    int64  
 4   cholestrol           303 non-null    int64  
 5   fasting_blood_sugar  303 non-null    int64  
 6   rest_ecg             303 non-null    int64  
 7   thalach              303 non-null    int64  
 8   exer_angina          303 non-null    int64  
 9   old_peak             303 non-null    float64
 10  slope                303 non-null    int64  
 11  ca                   303 non-null    int64  
 12  thalassemia          303 non-null    int64  
 13  target               303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [4]:
df.describe()

age      gender  chest_pain    rest_bps  cholestrol  \
count  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026   
std      9.082101    0.466011    1.032052   17.538143   51.830751   
min     29.000000    0.000000    0.000000   94.000000  126.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000   
max     77.000000    1.000000    3.000000  200.000000  564.000000   

       fasting_blood_sugar    rest_ecg     thalach  exer_angina    old_peak  \
count           303.000000  303.000000  303.000000   303.000000  303.000000   
mean              0.148515    0.528053  149.646865     0.326733    1.039604   
std               0.356198    0.525860   22.905161     0.469794    1.161075   
min               0.000000    0.000000   71.000000     0.000000    0.000000   
25%               0.000000    0.000000  133.500000     0.000000    0.000000   
50%               0.000000    1.000000  153.000000     0.000000    0.800000   
75%               0.000000    1.000000  166.000000     1.000000    1.600000   
max               1.000000    2.000000  202.000000     1.000000    6.200000   

            slope          ca  thalassemia      target  
count  303.000000  303.000000   303.000000  303.000000  
mean     1.399340    0.729373     2.313531    0.544554  
std      0.616226    1.022606     0.612277    0.498835  
min      0.000000    0.000000     0.000000    0.000000  
25%      1.000000    0.000000     2.000000    0.000000  
50%      1.000000    0.000000     2.000000    1.000000  
75%      2.000000    1.000000     3.000000    1.000000  
max      2.000000    4.000000     3.000000    1.000000

In [5]:
df.columns

Index(['age', 'gender', 'chest_pain', 'rest_bps', 'cholestrol',
       'fasting_blood_sugar', 'rest_ecg', 'thalach', 'exer_angina', 'old_peak',
       'slope', 'ca', 'thalassemia', 'target'],
      dtype='object')

In [6]:
df.drop(['chest_pain','fasting_blood_sugar','rest_ecg','thalach'
,'exer_angina','old_peak','slope','ca','thalassemia'],axis=1,inplace=True)

In [7]:
df.head()

age  gender  rest_bps  cholestrol  target
0   63       1       145         233       1
1   37       1       130         250       1
2   41       0       130         204       1
3   56       1       120         236       1
4   57       0       120         354       1

In [8]:
x=df.drop('target',axis=1)
y=df['target']

In [9]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.7,random_state=42)
xtrain.shape,xtest.shape

((212, 4), (91, 4))

In [14]:
from sklearn.linear_model import LogisticRegression

In [19]:
lgr=LogisticRegression()
lgr.fit(xtrain,ytrain)
pred_ytrain_lgr=lgr.predict(xtrain)
pred_ytest_lgr=lgr.predict(xtest)
pred_ytrain_lgr,pred_ytest_lgr

(array([1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
        1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
        1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
        1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
        0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
        1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
        0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
        1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
        1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1], dtype=int64),
 array([0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
        0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
        1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
        1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 

In [23]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [24]:
def acc_report(actual,predicted):
    acc_score=accuracy_score(actual,predicted)
    cm_matrix=confusion_matrix(actual,predicted)
    class_rep=classification_report(actual,predicted)
    print('the accuracy of tha model is ',acc_score)
    print(cm_matrix)
    print(class_rep)

In [25]:
acc_report(ytrain,pred_ytrain_lgr)

the accuracy of tha model is  0.6698113207547169
[[60 37]
 [33 82]]
              precision    recall  f1-score   support

           0       0.65      0.62      0.63        97
           1       0.69      0.71      0.70       115

    accuracy                           0.67       212
   macro avg       0.67      0.67      0.67       212
weighted avg       0.67      0.67      0.67       212



In [26]:
acc_report(ytest,pred_ytest_lgr)

the accuracy of tha model is  0.6703296703296703
[[28 13]
 [17 33]]
              precision    recall  f1-score   support

           0       0.62      0.68      0.65        41
           1       0.72      0.66      0.69        50

    accuracy                           0.67        91
   macro avg       0.67      0.67      0.67        91
weighted avg       0.67      0.67      0.67        91



## DECISION TREE

In [10]:
from  sklearn.tree import DecisionTreeClassifier

In [60]:
dt=DecisionTreeClassifier(max_depth=5,min_samples_split=5)
dt.fit(xtrain,ytrain)
pred_ytrain_dtr=dt.predict(xtrain)
pred_ytest_dtr=dt.predict(xtest)
pred_ytest_dtr,pred_ytrain_dtr

(array([0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
        0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
        0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
        0, 0, 0], dtype=int64),
 array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
        1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
        0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
        1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
        1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
        0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
        1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
      

In [61]:
acc_report(ytrain,pred_ytrain_dtr)

the accuracy of tha model is  0.8018867924528302
[[72 25]
 [17 98]]
              precision    recall  f1-score   support

           0       0.81      0.74      0.77        97
           1       0.80      0.85      0.82       115

    accuracy                           0.80       212
   macro avg       0.80      0.80      0.80       212
weighted avg       0.80      0.80      0.80       212



In [62]:
acc_report(ytest,pred_ytest_dtr)

the accuracy of tha model is  0.6153846153846154
[[27 14]
 [21 29]]
              precision    recall  f1-score   support

           0       0.56      0.66      0.61        41
           1       0.67      0.58      0.62        50

    accuracy                           0.62        91
   macro avg       0.62      0.62      0.62        91
weighted avg       0.62      0.62      0.62        91



## RANDOM FORESTC CLASSIFICATION

In [31]:
from sklearn.ensemble import RandomForestClassifier

In [63]:
rf=RandomForestClassifier(n_estimators=20,max_depth=3,verbose=1)
rf.fit(xtrain,ytrain)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed:    0.0s finished


RandomForestClassifier(max_depth=3, n_estimators=20, verbose=1)

In [64]:
pred_rf_train=rf.predict(xtrain)
pred_rf_test=rf.predict(xtest)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed:    0.0s finished


In [65]:
acc_report(ytrain,pred_rf_train)

the accuracy of tha model is  0.7358490566037735
[[62 35]
 [21 94]]
              precision    recall  f1-score   support

           0       0.75      0.64      0.69        97
           1       0.73      0.82      0.77       115

    accuracy                           0.74       212
   macro avg       0.74      0.73      0.73       212
weighted avg       0.74      0.74      0.73       212



In [66]:
acc_report(ytest,pred_rf_test)

the accuracy of tha model is  0.6593406593406593
[[28 13]
 [18 32]]
              precision    recall  f1-score   support

           0       0.61      0.68      0.64        41
           1       0.71      0.64      0.67        50

    accuracy                           0.66        91
   macro avg       0.66      0.66      0.66        91
weighted avg       0.66      0.66      0.66        91

